"""Write the generated layers to a Jekyll data file.

The site reads `_data/ascii/<name>.yml`; nothing in the published page depends on
this tool, so the emitted file is the artwork's source of truth and can be hand
edited afterwards in a monospaced editor.
"""

# Block scalar content is indented this far. `art: |2` sits at indent 4, so the
# text starts at column 6 and every art line keeps its own leading spaces.
ART_INDENT = " " * 6


def _block(rows):
    out = []
    for line in rows:
        out.append((ART_INDENT + line).rstrip() if line.strip() else "")
    return out


def render(layers, meta):
    lines = [
        "# Generated by tools/ascii_art/build_field.py -- see that directory's README.",
        "#",
        "# Plain text on a fixed %d-column grid, rendered by" % meta["columns"],
        "# _includes/atelier/ascii/field.liquid. The art is HTML-escaped at render",
        "# time, so < > & are safe to use here. Edit with a monospaced font.",
        "",
        "caption: >-",
    ]
    for line in meta["caption"].split("\n"):
        lines.append("  " + line.strip())
    lines += [
        "columns: %d" % meta["columns"],
        "rows: %d" % meta["rows"],
        "source:",
        "  title: %s" % _scalar(meta["source_title"]),
        "  url: %s" % _scalar(meta["source_url"]),
        "  license: %s" % _scalar(meta["source_license"]),
        "  recipe: %s" % _scalar(meta["recipe"]),
        "layers:",
    ]
    for name, rows in layers:
        lines.append("  - id: %s" % name)
        lines.append("    art: |2")
        lines += _block(rows)
    return "\n".join(lines) + "\n"


def _scalar(value):
    value = "" if value is None else str(value)
    if not value:
        return '""'
    if any(ch in value for ch in ":#{}[]&*!|>%@`") or value != value.strip():
        return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')
    return value


def write(path, layers, meta):
    text = render(layers, meta)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return text
